generic_app/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :diaries
  end
  resources :users do
    resources :affirmations
  end
  resources :users, only: [:signup, :login, :home]
  root "users#login_page"
  post 'users/signup', to: 'users#signup', as: 'signup'
  post 'users/login', to: 'users#login', as: 'login'
  get 'users/show', to: 'users#show', as: 'show'
  get 'users/signup_page', to: 'users#signup_page'
end

generic_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

generic_app/app/controllers/affirmations_controller.rb
class AffirmationsController < ApplicationController

  def create
    response = HTTParty.post(base_url + "users/#{cookies[:user_id]}/affirmations", body: body, headers: headers.merge!("Authorization" => cookies[:auth_token]))
    @affirmation=response['affirmation_id']
    redirect_to user_affirmation_path(cookies[:user_id], @affirmation)
  end

  def show
    if cookies[:auth_token]
      @response = HTTParty.get(base_url + "users/#{cookies[:user_id]}/affirmations/#{params['id']}", headers: headers.merge!("Authorization" => cookies[:auth_token]))
      @response= @response['affirmation']['note']
    else
      redirect_to root_path
    end
  end

  def index
    if cookies[:auth_token]
      @affirmations = HTTParty.get(base_url + "users/#{cookies[:user_id]}/affirmations", headers: headers.merge!("Authorization" => cookies[:auth_token]))
    else
      redirect_to root_path
    end
  end

  def edit
    response = HTTParty.get(base_url + "users/#{cookies[:user_id]}/affirmations/#{params['id']}", headers: headers.merge!("Authorization" => cookies[:auth_token]))
    @affirmation=response['affirmation']
  end

  def update
    response = HTTParty.patch(base_url + "users/#{cookies[:user_id]}/affirmations/#{params['id']}/", body: body, headers: headers.merge!("Authorization" => cookies[:auth_token]))
    redirect_to user_affirmations_path
  end

  def destroy
    response = HTTParty.delete(base_url + "users/#{cookies[:user_id]}/affirmations/#{params['id']}", headers: headers.merge!("Authorization" => cookies[:auth_token]))
    redirect_to user_affirmations_path
  end

  private
    def affirmation_params
      params[:affirmation]
    end

    def body
      affirmation_params.to_json
    end
end

generic_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
    def headers
      { 'Content-Type' => 'application/json' }
    end

    def base_url
      "http://localhost:3000/api/v1/"
    end
end

generic_app/app/controllers/diaries_controller.rb
class DiariesController < ApplicationController

  def new
  end

  def create
    response = HTTParty.post(base_url + "users/#{cookies[:user_id]}/diaries", body: body, headers: headers.merge!("Authorization" => cookies[:auth_token]))
    @diary=response['diary_id']
    redirect_to user_diary_path(cookies[:user_id], @diary)
  end


  def show
    if cookies[:auth_token]
      @response = HTTParty.get(base_url + "users/#{cookies[:user_id]}/diaries/#{params['id']}", headers: headers.merge!("Authorization" => cookies[:auth_token]))
    else
      redirect_to root_path
    end
  end

  def index
    if cookies[:auth_token]
      @diaries = HTTParty.get(base_url + "users/#{cookies[:user_id]}/diaries", headers: headers.merge!("Authorization" => cookies[:auth_token]))
    else
      redirect_to root_path
    end
  end
  private
    def diary_params
      params[:diary]
    end

    def body
      diary_params.to_json
    end
end

generic_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup_page
  end

  def signup
    response = HTTParty.post(base_url + "signup", body: body, headers: headers)
    cookies[:auth_token] = response['auth_token']
    cookies[:user_id] = response['user_id']
    binding.pry
    redirect_to show_path
  end

  def login_page
    cookies.delete :auth_token
    cookies.delete :user_id
  end

  def login
    response = HTTParty.post(base_url + "auth/login", body: body, headers: headers)
    if response['auth_token']
      cookies[:auth_token] = response['auth_token']
      cookies[:user_id] = response['user_id']
      redirect_to show_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    if cookies[:auth_token]
      @response = HTTParty.get(base_url + "user", headers: headers.merge!("Authorization" => cookies[:auth_token]))
    else
      redirect_to root_path
    end
  end

private
  def signup_params
    params[:anything]
  end

  def body
    signup_params.to_json
  end

end

generic_app/app/helpers/affirmations_helper.rb
module AffirmationsHelper
end

generic_app/app/helpers/application_helper.rb
module ApplicationHelper
  
end

generic_app/app/helpers/diaries_helper.rb
module DiariesHelper
end

generic_app/app/helpers/users_helper.rb
module UsersHelper
end

generic_app/app/views/affirmations/edit.html.slim
h1 Edit Affirmation

= simple_form_for :affirmation, method: :patch, url: user_affirmation_path do |f|
  = f.input :note, input_html: { value: @affirmation['note'] }
  = f.button :submit

=<link_to "Back", user_affirmations_path

generic_app/app/views/affirmations/index.html.slim
h2 Affirmations
table
  tr
    th Note

  -@affirmations.each do |affirmation|
    tr
      td = link_to affirmation['note'], user_affirmation_path(id: affirmation['id'])
      td =link_to 'Delete', user_affirmation_path(id: affirmation['id']), method: :delete, data: { confirm: 'Are you sure?' }
      td =link_to 'Edit', edit_user_affirmation_path(id: affirmation['id'])

br
br
=<link_to "New Affirmation",   new_user_affirmation_path(cookies[:user_id])
=<link_to "Back", user_path(cookies[:user_id])

generic_app/app/views/affirmations/new.html.slim
h1 New Affirmation

= simple_form_for :affirmation, method: :post, url: user_affirmations_path do |f|
  = f.input :note
  = f.button :submit

=<link_to "Back", user_path(cookies[:user_id])

generic_app/app/views/affirmations/show.html.slim
h1 Affirmation

b Note:
=<@response
br
=<link_to "Logout", root_path
=<link_to "Back", user_affirmations_path

generic_app/app/views/diaries/index.html.slim
h2 Diaries
table
  tr
    th Title
    th Entry

  -@diaries.each do |diary|
    tr
      td = link_to diary['title'], user_diary_path(id: diary['id'])
      td = diary['entry']

=<link_to "Back", user_path(cookies[:user_id])

generic_app/app/views/diaries/new.html.slim
h1 New Diary

= simple_form_for :diary, method: :post, url: user_diaries_path do |f|
  = f.input :title
  = f.input :entry
  = f.button :submit

=<link_to "Back", user_path(cookies[:user_id])

generic_app/app/views/diaries/show.html.slim
h1 Diary

b Title:
=<@response['title']
br
b Entry:
=<@response['entry']
br
b Date:
=< @response['date'].to_time
br
=<link_to "Logout", root_path
=<link_to "Back", user_diaries_path

generic_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GenericApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

generic_app/app/views/users/login_page.html.slim
h1 Login

= simple_form_for :anything, method: :post, url: login_path do |f|
  = f.input :email
  = f.input :password
  = f.button :submit

generic_app/app/views/users/show.html.slim
h1 Profile
b Name:
=<@response['name']
br
b Email:
=<@response['email']
br
=<link_to "New Diary",   new_user_diary_path(cookies[:user_id])
=<link_to "All Diaries",   user_diaries_path(cookies[:user_id])
br
=<link_to "New Affirmation",   new_user_affirmation_path(cookies[:user_id])
=<link_to "All Affirmations",   user_affirmations_path(cookies[:user_id])
br
=<link_to "Logout", root_path

generic_app/app/views/users/signup_page.html.slim
h1 Sign Up

= simple_form_for :anything, method: :post, url: signup_path do |f|
  = f.input :name
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.button :submit